# site_name: RoboticFFR SA.Advanced 
site_name: RoboticFFR SA.Advanced
nav:
  - Домашняя страница:
    - index.md
  - Документация:  
    - glossary.md 
    - business idea.md
    - characteristics.md
    - business prosess.md
    - requirements.md 
    - nfr.md
  - Модели:
    - architecture.md
  - Интерфейсы:
    - design.md
    - api.md
    - api_tablo.md
    - api_screen.md
  - Задачи: 
    - tasks.md
    - mvp.md
    - testscenarios.md
    - TestScenariosR1.md
theme: 
  name: material #mkdocs  #readthedocs  # или "material" для красивого дизайна
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: lime
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

plugins:
  # - social
  - search
  - swagger-ui-tag



markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  # - pymdownx.emoji:
    #  emoji_index: !!python/name:materialx.emoji.twemoji
     # emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2023 <a href="https://github.com/tsvetkoviu"  target="_blank" rel="noopener">Ilia Tsvetkov</a>
